# This is a basic workflow to help you get started with Actions

name: Angular-PABV-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup nodejs
        run: actions/setup-node@v4.1.0

      - name: Install dependencies
        run: npm install

      - name: Build Angular APP
        run: npm run build:prod

      - name: Deploy Github pages
      - uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: dist/angular_proyect_pabv/browser
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
